### ISSUE TITLE
bbr-acs/ebbr/config/EBBR.seq: missing tests SimpleFileSystemProtocolTest and BlockIOProtocolTest 

### ISSUE THREAD

**Issue by xypron** [ARM-software/bbr-acs#12]
SimpleFileSystemProtocolTest and BlockIOProtocolTest are missing in EBBR.seq though they are required by the EBBR:

```
EFI_BLOCK_IO_PROTOCOL           | Required for block device access
EFI_SIMPLE_FILE_SYSTEM_PROTOCOL | Required if booting from block device is supported
```

**Comment by xypron** [comment]
After the SCT you should check that the FAT file system is not corrupted using dosfsck.

**Comment by edhay** [comment]
Dear @xypron, 

    The solution for this issue is under discussion.
Will update the outcome in the next week.

ACS Support

**Comment by edhay** [comment]
SimpleFileSystemProtocolTest and BlockIOProtocolTest are now enabled and available in
https://github.com/ARM-software/bbr-acs/blob/main/ebbr/config/EBBR_extd_run.seq
