### ISSUE TITLE
./build-scripts/build_ebbr.sh compile error

### ISSUE THREAD

**Issue by WangYin3** [ARM-software/bbr-acs#29]
looks like some patch fail:
...
----------------------------------------------------------------------
Ran 285 tests in 0.561s

OK
make[1]: Leaving directory '/home/yin/c/acs/bbr-acs/ebbr/scripts/edk2/BaseTools/Tests'
make: Leaving directory '/home/yin/c/acs/bbr-acs/ebbr/scripts/edk2/BaseTools'
1 out of 1 hunk FAILED
3 out of 3 hunks FAILED
1 out of 1 hunk FAILED
6 out of 6 hunks FAILED
1 out of 1 hunk FAILED
1 out of 1 hunk FAILED
2 out of 2 hunks FAILED
1 out of 1 hunk FAILED
1 out of 2 hunks FAILED
1 out of 1 hunk FAILED
1 out of 1 hunk FAILED
1 out of 1 hunk FAILED
Applying SCT patch ...
patching file uefi-sct/SctPkg/CommonGenFramework.sh
patching file uefi-sct/SctPkg/Config/Data/Category.ini
patching file uefi-sct/SctPkg/Library/SctGuidLib/SctGuidLib.inf
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/ImageServices/BlackBoxTest/ImageBBTestConformance.c
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/ImageServices/BlackBoxTest/ImageBBTestFunction.c
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/ImageServices/BlackBoxTest/Misc.h
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestConformance.c
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestFunction.c
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestMain.c
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/EfiCompliant/BlackBoxTest/Dependency/Config/EfiCompliant.ini
patching file uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/VariableServices/BlackBoxTest/AuthVariableServicesBBTestConformance.c
Hunk #1 FAILED at 291.
1 out of 1 hunk FAILED -- saving rejects to file uefi-sct/SctPkg/TestCase/UEFI/EFI/RuntimeServices/VariableServices/BlackBoxTest/AuthVariableServicesBBTestConformance.c.rej
patching file uefi-sct/SctPkg/TestInfrastructure/SCT/Drivers/StandardTest/StandardTest.c

Build failed: error while running do_build at line 157 in ./build-scripts/build-sct.sh for [][].

**Comment by edhay** [comment]
Hi @WangYin3 , 
Thank you for reporting this issue. Will update the progress and solution

**Comment by edhay** [comment]
Hi WangYin3,
  The issue is solved through the commit: 
https://github.com/ARM-software/bbr-acs/commit/ddce83057fff554d8b8b942b9447f9fec7b9cc0c

Please try the build with the latest code and confirm if okay.
