### ISSUE TITLE
Remove SCT SMBIOS tests

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bbr-acs#37]
Remove SCT SMBIOS tests as they are already covered by FWTS. 

https://github.com/ARM-software/bbr-acs/blob/44943eb3fd239fde1002107568b0a5f154949f7f/common/sct-tests/sbbr-tests/SbbrSmbios/BlackBoxTest/SbbrSmbiosBBTestFunction.c

**Comment by edhay** [comment]
Hi Sunny,
  The issue is closed by the PR https://github.com/ARM-software/bbr-acs/pull/40
The SBBR SMBIOS tests have been removed.

**Comment by sunnywang-arm** [comment]
Thanks, Edhaya. 
Close the issue.
