### ISSUE TITLE
Enhancement: option to build SCT or FWTS (only) in build_sbbr.sh

### ISSUE THREAD

**Issue by edhay** [ARM-software/bbr-acs#74]
build_sbbr.sh by default builds both FWTS and UEFI-SCT when run.

It could take options to build only UEFI-SCT or FWTS

build_sbbr.sh fwts  //builds only FWTS
build_sbbr.sh uefi-sct // builds only UEFI-SCT

When no argument is given retain the existing behavior

**Comment by chetan-rathore** [comment]
Hi @edhay,

Thanks for the ticket, it is a good enhancement. 
ACS team will investigate on adding this option in bbr build and will share the timelines.

Thanks,
ACS team
