### ISSUE TITLE
SR ACS v24.03_2.1.0 - The ACS version in SCT summary.log is wrong  

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bbr-acs#75]
It is showing "Arm ACS Version: v2.0.0-BETA-0" even if we use ACS 24.03_2.1.0

Moreover, can we add "SCT version" and "built date" into the version string showing in Summary.log?

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

We are working on the version changes and will upstream the changes soon.
The addition of SCT version and built date will need some investigation, as Summary.log is generated from SCT tool itself.

Thanks,
ACS team
